-- ******************************** SqlDBM: Snowflake ********************************
-- * Generated by SqlDBM: Snowflake Demo, v142 vs v136 by retinder.labana@sqldbm.com *

ALTER TABLE ADWORKS.FactResellerSales
    DROP CONSTRAINT FK_FactResellerSales_447;

ALTER TABLE ADWORKS.FactResellerSales
    DROP CONSTRAINT FK_FactResellerSales_455;

ALTER TABLE ADWORKS.FactResellerSales
    DROP CONSTRAINT FK_FactResellerSales_445;

ALTER TABLE ADWORKS.FactResellerSales
    DROP CONSTRAINT FK_FactResellerSales_449;

ALTER TABLE ADWORKS.DimCustomer
    DROP CONSTRAINT FK_DimCustomer_401;

ALTER TABLE ADWORKS.DimCustomer
    DROP CONSTRAINT PK_DimCustomer;

DROP TABLE ADWORKS.FactInternetSales;

DROP TABLE ADWORKS.DimReseller;

DROP TABLE ADWORKS.DimEmployee;

DROP TABLE RETINDER.TRIPS;

DROP TABLE RETINDER.TABLE_NAME;

DROP TABLE table_53;

DROP TABLE table_43;

DROP TABLE table_42;

DROP TABLE table_41;

DROP TABLE RETINDER.STUDENTS;

DROP TABLE RETINDER.STUDENT;

DROP TABLE RETINDER.FAQ;

DROP TABLE RETINDER.DWH_GEO_HIERARCHY;

CREATE SCHEMA AAP;

CREATE SCHEMA ACT;

DROP SCHEMA RETINDER;

DROP FILE FORMAT "SQLDBM_DEMO.RETINDER.CSV";

ALTER TABLE ADWORKS.NewFactCurrencyRate
    DROP COLUMN AverageRate;

ALTER TABLE ADWORKS.NewFactCurrencyRate
    ADD COLUMN AverageRate111 float;

ALTER TABLE ADWORKS.FactSurveyResponse
    SET COMMENT = 'add';

ALTER TABLE ADWORKS.DimSalesTerritory
    ADD COLUMN SalesOrderNumber varchar(20) NOT NULL;

ALTER TABLE ADWORKS.FactResellerSales
    DROP COLUMN ProductKey;

ALTER TABLE ADWORKS.FactResellerSales
    DROP COLUMN ResellerKey;

ALTER TABLE ADWORKS.FactResellerSales
    DROP COLUMN SalesTerritoryKey;

ALTER TABLE ADWORKS.FactResellerSales
    DROP COLUMN SalesOrderLineNumber;

ALTER TABLE ADWORKS.FactResellerSales
    ADD COLUMN "Product Key" number(38,0) NOT NULL;

ALTER TABLE ADWORKS.FactResellerSales
    ADD COLUMN "Sales Order Line Number" number(38,0) NOT NULL;

ALTER TABLE ADWORKS.DimCurrency
    DROP COLUMN CurrencyName;

ALTER TABLE ADWORKS.DimCurrency
    ADD COLUMN CurrencyName22 varchar(50) NOT NULL COMMENT 'Name of the Currency';

ALTER TABLE ADWORKS.DimOrganization
    DROP COLUMN ParentOrganizationKey;

ALTER TABLE ADWORKS.DimOrganization
    ADD COLUMN tester number(38,0);

ALTER TABLE ADWORKS.DimOrganization
    ADD COLUMN tester_1 integer NOT NULL;

ALTER TABLE ADWORKS.DimCustomer
    DROP COLUMN CustomerKey;

ALTER TABLE ADWORKS.DimCustomer
    DROP COLUMN GeographyKey;

ALTER TABLE ADWORKS.DimCustomer
    ADD COLUMN CustomerKey2 number(38,0) AUTOINCREMENT NOT NULL COMMENT 'Customer Identifier';

ALTER TABLE ADWORKS.DimCustomer
    ADD COLUMN GeographyKey333 number(38,0) COMMENT 'Geographic informatio';

ALTER TABLE ADWORKS.DimDepartmentGroup
    ADD COLUMN id integer NOT NULL;

ALTER TABLE ADWORKS."Dim Employee"
    ALTER COLUMN EmployeeKey COMMENT '';

ALTER TABLE ADWORKS.FactSurveyResponse
    ADD CONSTRAINT PK_3 PRIMARY KEY (SurveyResponseKey);

ALTER TABLE ADWORKS.FactResellerSales
    ADD CONSTRAINT PK_8 PRIMARY KEY (SalesOrderNumber);

ALTER TABLE ADWORKS.DimCustomer
    ADD CONSTRAINT PK_DimCustomer PRIMARY KEY (CustomerKey2);

DROP VIEW RETINDER.TESTQUAL;

DROP VIEW ADWORKS.DIM_PRODUCT_CAT_SUBCAT_V;

CREATE VIEW SQLDBM_DEMO.ADWORKS.DIM_PRODUCT_CAT_SUBCAT_V(
	"ProductKey",
	"ProductAlternateKey",
	"ProductSubcategoryKey",
	"WeightUnitMeasureCode",
	"SizeUnitMeasureCode",
	"EnglishProductName",
	"StandardCost",
	"FinishedGoodsFlag",
	"Color",
	"SafetyStockLevel",
	"ReorderPoint",
	"ListPrice",
	"Size",
	"SizeRange",
	"Weight",
	"DaysToManufacture",
	"ProductLine",
	"DealerPrice",
	"Class",
	"Style",
	"ModelName",
	"EnglishDescription",
	"Status",
	"ProductCategoryKey",
	"ProductCategoryAlternateKey",
	"EnglishProductCategoryName",
	"EnglishProductSubcategoryName"
) COMMENT='Product details with cat and subcat english names. For fwd/rev engineering'
 as
(
WITH cat_subcat as (
SELECT cat.* , sub."ProductSubcategoryKey" as "SubProductSubcategoryKey", sub."EnglishProductSubcategoryName"  FROM "DimProductCategory" cat
inner join  "DimProductSubcategory" sub
on  cat."ProductCategoryKey" = sub."ProductCategoryKey"
) 
  select 
 "ProductKey"           
, "ProductAlternateKey"  
, "ProductSubcategoryKey"
, "WeightUnitMeasureCode"
, "SizeUnitMeasureCode"  
, "EnglishProductName"   
, "StandardCost"         
, "FinishedGoodsFlag"    
, "Color"                
, "SafetyStockLevel"     
, "ReorderPoint"         
, "ListPrice"            
, "Size"                 
 ,"SizeRange"            
 ,"Weight"               
 ,"DaysToManufacture"    
 ,"ProductLine"          
 ,"DealerPrice"          
 ,"Class"                
 ,"Style"                
 ,"ModelName"            
 ,"EnglishDescription"   
 ,"Status"                   
,"ProductCategoryKey"         
,"ProductCategoryAlternateKey"
,"EnglishProductCategoryName" 
,"EnglishProductSubcategoryName"
 from "DimProduct" prod
  left join cat_subcat 
  on prod."ProductSubcategoryKey" = cat_subcat."SubProductSubcategoryKey"
);

ALTER TABLE table_34_1
    ADD CONSTRAINT FK_1 FOREIGN KEY (SurveyResponseKey) REFERENCES ADWORKS.FactSurveyResponse (SurveyResponseKey);

ALTER TABLE ADWORKS.DimSalesTerritory
    ADD CONSTRAINT FK_2 FOREIGN KEY (SalesOrderNumber) REFERENCES ADWORKS.FactResellerSales (SalesOrderNumber);

ALTER TABLE ADWORKS.FactResellerSales
    ADD CONSTRAINT FK_FactResellerSales_445 FOREIGN KEY ("Product Key") REFERENCES ADWORKS.DimProduct (ProductKey);

ALTER TABLE ADWORKS.FactResellerSales
    ADD CONSTRAINT FK_FactResellerSales_449 FOREIGN KEY (EmployeeKey) REFERENCES ADWORKS."Dim Employee" (EmployeeKey);

ALTER TABLE ADWORKS.DimCustomer
    ADD CONSTRAINT FK_DimCustomer_401 FOREIGN KEY (GeographyKey333) REFERENCES ADWORKS.DimGeography (GeographyKey);

ALTER TABLE ADWORKS.FactResellerSales
    CLUSTER BY ( SalesOrderNumber );