-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Sample 101, v3 vs v1 by retinder.labana@sqldbm.com *

ALTER TABLE ADWORKS."DimCurrency"
    ADD COLUMN col_4 varchar(60) NOT NULL;

CREATE TABLE hub_
(
 md5_hub_ binary NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL,
 rec_src  varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_hub_ )
);