-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Yum Demo, v3 vs v2 by retinder.labana@sqldbm.com *

ALTER TABLE ADWORKS."DimAccount"
    ALTER COLUMN "AccountCodeAlternateKey" COMMENT 'tester';