-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** Sequence_1
CREATE SEQUENCE Sequence_1
START WITH 1
INCREMENT BY 1;
