-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 22 by retinder.labana@sqldbm.com *


-- ************************************** Tag_2
CREATE TAG Tag_2 ALLOWED_VALUES 'val 2';
