-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 22 by retinder.labana@sqldbm.com *


-- ************************************** Tag_1
CREATE TAG Tag_1 ALLOWED_VALUES 'val';
