-- ******************************** SqlDBM: Snowflake ********************************
-- * Generated by SqlDBM: Snowflake Demo, v145 vs v140 by retinder.labana@sqldbm.com *

CREATE SCHEMA AAP;

CREATE SCHEMA ACT;

ALTER TABLE ADWORKS.DimProductCategory
    ADD COLUMN id integer NOT NULL;

-- Attention! Cannot change column data type.

ALTER TABLE ADWORKS.DimCurrency
    ALTER COLUMN CurrencyAlternateKey SET DATA TYPE dsf;

ALTER TABLE ADWORKS.DimCurrency
    ADD COLUMN id  NOT NULL;

CREATE TABLE table_41
(
 username varchar(50) NOT NULL, 
 date     datetime NOT NULL, 
 col_1    varchar NOT NULL 

);

ALTER TABLE ADWORKS.FactResellerSales
    CLUSTER BY ( SalesOrderNumber );