-- ******************************** SqlDBM: Snowflake ********************************
-- * Generated by SqlDBM: Snowflake Demo, v155 vs v150 by retinder.labana@sqldbm.com *

ALTER TABLE ADWORKS.DimGeography
    ADD COLUMN id integer NOT NULL;

-- Attention! Cannot change column data type.

ALTER TABLE ADWORKS.DimCurrency
    ALTER COLUMN CurrencyAlternateKey SET DATA TYPE integer;

ALTER TABLE ADWORKS.FactSalesQuota
    ADD CONSTRAINT VFK (EmployeeKey);

ALTER TABLE ADWORKS.FactFinance
    ADD CONSTRAINT VPK (FinanceKey, OrganizationKey, DepartmentGroupKey, ScenarioKey, AccountKey);

ALTER TABLE ADWORKS.FactProductInventory
    ADD CONSTRAINT VPK (DateKey, MovementDate);

ALTER TABLE ADWORKS.FactProductInventory
    ADD CONSTRAINT VFK (ProductKey);

ALTER TABLE ADWORKS.DimOrganization
    ADD CONSTRAINT VFK (CurrencyKey);

CREATE TABLE table_46
(
 username varchar(50) NOT NULL, 
 date     datetime NOT NULL 

);

CREATE TABLE table_45
(
 username varchar(50) NOT NULL, 
 date     datetime NOT NULL, 
 col_1    varchar NOT NULL 

);

CREATE TABLE table_44
(
 username varchar(50) NOT NULL, 
 date     datetime NOT NULL 

);