-- ********************************* SqlDBM: Snowflake ********************************
-- * Generated by SqlDBM: Snowflake Demo 12, v22 vs v21 by retinder.labana@sqldbm.com *

CREATE TABLE table_29
(
 username varchar NOT NULL 

);

CREATE TABLE table_28
(
 username varchar NOT NULL 

);

CREATE TABLE hub__1
(
 username varchar NOT NULL, 
 md5_hub_ binary NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL,
 rec_src  varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_hub_ )
);