-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Snowflake Demo, v37 vs v33 by retinder.labana@sqldbm.com *

ALTER TABLE EDW.sqldbm_ChildDemo
    ADD COLUMN id int NOT NULL;

CREATE TABLE SFLK_DATA.Sample_test
(
 col_1 date NOT NULL 

);