-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Snowflake Demo, v44 vs v41 by retinder.labana@sqldbm.com *

ALTER TABLE EDW.sqldbm_DimDepartmentGroup
    ADD COLUMN id_1 integer NOT NULL;

-- Attention! Cannot change column data type.

ALTER TABLE EDW.sqldbm_DimAccount
    ALTER COLUMN id SET DATA TYPE ABC;