-- ************************************* SqlDBM: BigQuery ************************************
-- * Generated by SqlDBM: Google Big Query Webinar, v49 vs v42 by retinder.labana@sqldbm.com *

DROP TABLE table_26;

DROP TABLE table_21;

DROP TABLE serge.strct_tbl;

DROP TABLE `serge.d-1`;

DROP TABLE `serge_caseInsens.d-1`;

DROP TABLE serge.d1;

CREATE SCHEMA mydataset
OPTIONS(is_case_insensitive = false);

DROP SCHEMA Project.shaped_canyon_389209;

DROP SCHEMA serge;

DROP SCHEMA serge_caseInsens;

DROP VIEW view_1;

CREATE VIEW mydataset.usa_male_names_new(name, number) AS (
SELECT id AS matching_rows
FROM Sequences
WHERE EXISTS(SELECT * FROM UNNEST(some_numbers) AS x WHERE x = 5)

);

CREATE VIEW mydataset.usa_male_names(name, number) AS (
SELECT id AS matching_rows
FROM Sequences
WHERE EXISTS(SELECT * FROM UNNEST(some_numbers) AS x WHERE x = 5)

);

ALTER TABLE operations.dim_time
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_time
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.fact_inventory
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.fact_inventory
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_customer
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_customer
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_customer
 SET OPTIONS(
description = 'Customer information');

ALTER TABLE operations.dim_location
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_location
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_location
 SET OPTIONS(
description = 'List of locations and it''s details');

ALTER TABLE operations.dim_employee
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_employee
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_employee
 SET OPTIONS(
description = 'Employee List');

ALTER TABLE operations.fact_sales
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.fact_sales
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_product
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_product
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_product
 SET OPTIONS(
description = 'product list and its specs');

ALTER TABLE operations.dim_category
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_category
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_category
ALTER COLUMN category_name SET OPTIONS(
description = 'name of the category');

ALTER TABLE operations.dim_category
ALTER COLUMN description SET OPTIONS(
description = 'description for the category');

ALTER TABLE operations.dim_category
 SET OPTIONS(
description = 'Category list and it''s details');

ALTER TABLE operations.dim_supplier
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_supplier
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_supplier
 SET OPTIONS(
description = 'supplier information');

ALTER TABLE operations.dim_channel
ADD COLUMN created_by string OPTIONS(description = 'user who created the entery');

ALTER TABLE operations.dim_channel
ADD COLUMN created_on timestamp OPTIONS(description = 'timestamps when the entry was created');

ALTER TABLE operations.dim_channel
 SET OPTIONS(
description = 'Channel list and locations');