-- ******************************** SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Snowflake Demo 12, v6 vs v5 by retinder.labana@sqldbm.com *

ALTER TABLE hub_
    ADD COLUMN new_col int NOT NULL;