-- ********************************* SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Snowflake Demo 12, v6 vs stage by retinder.labana@sqldbm.com *

ALTER SCHEMA ADWORKS
    SET COMMENT = 'tesetr 101';

ALTER TABLE ADWORKS.ChildDemo
    ADD COLUMN id int NOT NULL;

CREATE TABLE hub_
(
 md5_hub_ binary NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL,
 rec_src  varchar(16777216) NOT NULL,
 new_col  int NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_hub_ )
);