-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** procedure_1
CREATE PROCEDURE procedure_1()
  Returns string -- Please specify return type
  Language Javascript
  Comment = 'No Comment Provided'

AS
$$
  // Please type procedure definition 
$$;
