-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** marts.orders
CREATE EXTERNAL TABLE marts.orders
(
 order_id       int NOT NULL CONSTRAINT pk_6 PRIMARY KEY,
 custkey        int NOT NULL COMMENT 'Customer Identifier' CONSTRAINT fk_3_2 REFERENCES marts.customers,
 order_status   string DEFAULT 'active',
 order_date     date NOT NULL,
 order_date_ntz timestamp_ntz,
 required_date  date NOT NULL,
 shipped_date   date,
 store_id       int NOT NULL,
 staff_id       int NOT NULL
)
USING DELTA
 COMMENT 'table stores the sales order’s header information including customer, order status, order date, required date, shipped date.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.feature.allowColumnDefaults = 'supported', delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name', delta.feature.deletionVectors = 'supported', delta.feature.columnMapping = 'supported', delta.feature.timestampNtz = 'supported', delta.feature.invariants = 'supported')
 LOCATION 's3://sqldbm-databricks-external/hazal_test/orders_external';
