-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

CREATE VIEW marts.nation_region 
AS
 SELECT na.nationkey , na.regionkey, re.name
         FROM marts.nation AS na 
         INNER JOIN marts.region AS re 
            ON na.regionkey = re.regionkey;
