-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

CREATE VIEW marts.legacy_customer 
COMMENT 'View for legacy customers with over 5 years of loyalty'
AS
 SELECT custkey, FirstName FROM marts.customers WHERE BirthDate >= '1975-01-01';
