-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *


-- ************************************** mydataset.usa_male_names
CREATE VIEW mydataset.usa_male_names(name, number) AS (
SELECT id AS matching_rows
FROM Sequences
WHERE EXISTS(SELECT * FROM UNNEST(some_numbers) AS x WHERE x = 5)

);
