-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 22 by retinder.labana@sqldbm.com *


-- ************************************** myschema.dummy_2
CREATE VIEW myschema.dummy_2(pkid test ) as /* test table text */ select 1;

-- comments are supported where we expect to put it
--;
