-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 22 by retinder.labana@sqldbm.com *


-- ************************************** myschema.dummy
CREATE /* test t@ble text */ view myschema.dummy(pkid test ) as select 1;
