-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

CREATE MATERIALIZED VIEW products.stocks_materialized_v 
AS
 SELECT
  *
FROM
  products.stocks;
