-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *


-- ************************************** view_1
CREATE VIEW view_1
AS (
  -- Please type query_expression here
);
