-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: Sample Project by retinder.labana@sqldbm.com *

-- ************************************** view_1
CREATE VIEW view_1

  Comment = 'No Comment Provided'

AS
(
  -- Please type view definition here

);
