-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** `ABC.operations`.dim_category

CREATE TABLE `ABC.operations`.dim_category
(
category_id   int64 NOT NULL PRIMARY KEY NOT ENFORCED,
category_name string,
description   string,
subcategories array<string>
)
OPTIONS(friendly_name = 'category');
