-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** ADWORKS.FactProductInventory
CREATE OR REPLACE TABLE ADWORKS.FactProductInventory
(
 ProductKey   number(38,0) NOT NULL,
 DateKey      number(38,0) NOT NULL,
 MovementDate date NOT NULL,
 UnitCost     number(38,0) NOT NULL,
 UnitsIn      number(38,0) NOT NULL,
 UnitsOut     number(38,0) NOT NULL,
 UnitsBalance number(38,0) NOT NULL,

 CONSTRAINT FK_FactProductInventory_443 FOREIGN KEY ( DateKey ) REFERENCES ADWORKS.DimDate ( DateKey )
);
