-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** ADWORKS.NewFactCurrencyRate
CREATE TABLE ADWORKS.NewFactCurrencyRate
(
 AverageRate111 float,
 CurrencyID     varchar(3),
 CurrencyDate   date,
 EndOfDayRate   float,
 CurrencyKey    number(38,0),
 DateKey        number(38,0),

 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES ADWORKS.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_NewFactCurrencyRate_471 FOREIGN KEY ( DateKey ) REFERENCES ADWORKS.DimDate ( DateKey )
);
