-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** ADWORKS."Dim Employee"
CREATE TABLE ADWORKS."Dim Employee"
(
 EmployeeKey                          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentEmployeeKey333                 number(38,0),
 EmployeeNationalIDAlternateKey       varchar(15),
 ParentEmployeeNationalIDAlternateKey varchar(15),
 SalesTerritoryKey                    number(38,0),
 "Customer First Name"                  varchar(50) NOT NULL,
 LastName                             varchar(50) NOT NULL,
 MiddleName                           varchar(50),
 NameStyle                            number(38,0) NOT NULL,
 Title                                varchar(50),
 HireDate                             date,
 BirthDate                            date,
 LoginID                              varchar(256),
 EmailAddress                         varchar(50),
 Phone                                varchar(25),
 MaritalStatus                        varchar(1),
 EmergencyContactName                 varchar(50),
 EmergencyContactPhone                varchar(25),
 SalariedFlag                         number(38,0),
 Gender                               varchar(1),
 PayFrequency                         number(38,0),
 BaseRate                             number(38,0),
 VacationHours                        number(38,0),
 SickLeaveHours                       number(38,0),
 CurrentFlag                          number(38,0) NOT NULL,
 SalesPersonFlag                      number(38,0) NOT NULL,
 DepartmentName                       varchar(50),
 StartDate                            date,
 EndDate                              date,
 Status                               varchar(50),

 CONSTRAINT PK_DimEmployee PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_403 FOREIGN KEY ( ParentEmployeeKey333 ) REFERENCES ADWORKS."Dim Employee" ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_405 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES ADWORKS.DimSalesTerritory ( SalesTerritoryKey )
)
COMMENT = 'This table holds all Employee Information';
