-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** ADWORKS.DimSalesTerritory
CREATE OR REPLACE TABLE ADWORKS.DimSalesTerritory
(
 SalesTerritoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SalesTerritoryAlternateKey number(38,0),
 SalesOrderNumber           varchar(20) NOT NULL,
 SalesTerritoryRegion       varchar(50) NOT NULL,
 SalesTerritoryCountry      varchar(50) NOT NULL,
 SalesTerritoryGroup        varchar(50),

 CONSTRAINT PK_DimSalesTerritory PRIMARY KEY ( SalesTerritoryKey ),
 CONSTRAINT FK_37_1 FOREIGN KEY ( SalesOrderNumber ) REFERENCES ADWORKS.FactResellerSales ( SalesOrderNumber )
)
COMMENT = 'Sales Territory data';
