-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** ADWORKS.DimOrganization
CREATE TABLE ADWORKS.DimOrganization
(
 OrganizationKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 tester                number(38,0),
 PercentageOfOwnership varchar(16),
 OrganizationName      varchar(50),
 tester_1              integer NOT NULL,
 CurrencyKey           number(38,0),

 CONSTRAINT PK_DimOrganization PRIMARY KEY ( OrganizationKey )
)
COMMENT = 'Dimension for Organizational Data';
