-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** ADWORKS.DimDepartmentGroup
CREATE TABLE ADWORKS.DimDepartmentGroup
(
 DepartmentGroupKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentDepartmentGroupKey number(38,0),
 DepartmentGroupName      varchar(50),

 CONSTRAINT PK_DimDepartmentGroup PRIMARY KEY ( DepartmentGroupKey )
)
COMMENT = 'Dimension for Department groups';
