-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** ADWORKS.DimSalesTerritory
CREATE TABLE ADWORKS.DimSalesTerritory
(
 SalesTerritoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SalesTerritoryAlternateKey number(38,0),
 SalesTerritoryRegion       varchar(50) NOT NULL,
 SalesTerritoryCountry      varchar(50) NOT NULL,
 SalesTerritoryGroup        varchar(50),
 username                   varchar NOT NULL, -- From template: "metadata"

 CONSTRAINT PK_DimSalesTerritory PRIMARY KEY ( SalesTerritoryKey )
)
COMMENT = 'Sales Territory data';
