-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** ADWORKS.FactInternetSales
CREATE TABLE ADWORKS.FactInternetSales
(
 ProductKey            number(38,0) NOT NULL,
 OrderDateKey          number(38,0) NOT NULL,
 DueDateKey            number(38,0) NOT NULL,
 ShipDateKey           number(38,0) NOT NULL,
 CustomerKey           number(38,0) NOT NULL,
 PromotionKey          number(38,0) NOT NULL,
 CurrencyKey           number(38,0) NOT NULL,
 SalesTerritoryKey     number(38,0) NOT NULL,
 SalesOrderNumber      varchar(20) NOT NULL,
 SalesOrderLineNumber  number(38,0) NOT NULL,
 RevisionNumber        number(38,0) NOT NULL,
 OrderQuantity         number(38,0) NOT NULL,
 UnitPrice             number(38,0) NOT NULL,
 ExtendedAmount        number(38,0) NOT NULL,
 UnitPriceDiscountPct  float NOT NULL,
 DiscountAmount        float NOT NULL,
 ProductStandardCost   number(38,0) NOT NULL,
 TotalProductCost      number(38,0) NOT NULL,
 SalesAmount           number(38,0) NOT NULL,
 TaxAmt                number(38,0) NOT NULL,
 Freight               number(38,0) NOT NULL,
 CarrierTrackingNumber varchar(25),
 CustomerPONumber      varchar(25),
 username              varchar NOT NULL, -- From template: "metadata"

 CONSTRAINT FK_FactInternetSales_427 FOREIGN KEY ( ProductKey ) REFERENCES ADWORKS.DimProduct ( ProductKey ),
 CONSTRAINT FK_FactInternetSales_429 FOREIGN KEY ( CustomerKey ) REFERENCES ADWORKS.DimCustomer ( CustomerKey ),
 CONSTRAINT FK_FactInternetSales_431 FOREIGN KEY ( PromotionKey ) REFERENCES ADWORKS.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactInternetSales_433 FOREIGN KEY ( CurrencyKey ) REFERENCES ADWORKS.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactInternetSales_435 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES ADWORKS.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactInternetSales_437 FOREIGN KEY ( OrderDateKey ) REFERENCES ADWORKS.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_439 FOREIGN KEY ( DueDateKey ) REFERENCES ADWORKS.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_441 FOREIGN KEY ( ShipDateKey ) REFERENCES ADWORKS.DimDate ( DateKey )
)
COMMENT = 'Fact table to hold Currency Data';
