-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** ADWORKS.NewFactCurrencyRate
CREATE TABLE ADWORKS.NewFactCurrencyRate
(
 AverageRate  float,
 CurrencyID   varchar(3),
 CurrencyDate date,
 EndOfDayRate float,
 CurrencyKey  number(38,0),
 DateKey      number(38,0),
 username     varchar NOT NULL, -- From template: "metadata"

 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES ADWORKS.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_NewFactCurrencyRate_471 FOREIGN KEY ( DateKey ) REFERENCES ADWORKS.DimDate ( DateKey )
);
