-- ************************** SqlDBM: Snowflake *************************
-- ******* Generated by SqlDBM: Re-1 by retinder.labana@sqldbm.com ******

-- ************************************** dbo.Product
CREATE TABLE dbo.Product
(
 ProductId      integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductName    nvarchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      number(12,2),
 IsDiscontinued boolean NOT NULL DEFAULT ((0)),
 col_6           NOT NULL,

 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( SupplierId, ProductName ),
 CONSTRAINT FK_Product_SupplierId_Supplier FOREIGN KEY ( SupplierId ) REFERENCES dbo.Supplier ( SupplierId )
)
COMMENT = 'Basic information 
about Product';
