-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of 'Msql server - snowflake' by retinder.labana@sqldbm.com *

-- ************************************** dbo.Supplier
CREATE TABLE dbo.Supplier
(
 SupplierId  integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 CompanyName sample101 NOT NULL,
 Phone       nvarchar(20),

 CONSTRAINT PK_Supplier PRIMARY KEY ( SupplierId ),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE ( CompanyName )
)
COMMENT = 'Basic information 
about Supplier';
