-- ************************** SqlDBM: Snowflake *************************
-- ******* Generated by SqlDBM: Re-1 by retinder.labana@sqldbm.com ******

-- ************************************** dbo.OrderItem
CREATE TABLE dbo.OrderItem
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice number(12,2) NOT NULL,
 Quantity  integer NOT NULL,

 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order FOREIGN KEY ( OrderId ) REFERENCES dbo."Order" ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product FOREIGN KEY ( ProductId ) REFERENCES dbo.Product ( ProductId )
)
COMMENT = 'Information about
like Price, Quantity';
