-- ************************** SqlDBM: Snowflake *************************
-- ******* Generated by SqlDBM: Re-1 by retinder.labana@sqldbm.com ******

-- ************************************** dbo."Order"
CREATE TABLE dbo."Order"
(
 OrderId     integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 OrderNumber nvarchar(10),
 CustomerId  integer NOT NULL,
 OrderDate   datetime NOT NULL DEFAULT (getdate()),
 TotalAmount number(12,2) NOT NULL,

 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer FOREIGN KEY ( CustomerId ) REFERENCES dbo.Customer ( CustomerId )
)
COMMENT = 'Order information
like Date, Amount';
