-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of 'Msql server - snowflake' by retinder.labana@sqldbm.com *

-- ************************************** dbo.Customer
CREATE TABLE dbo.Customer
(
 CustomerId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 CustomerName nvarchar(40) NOT NULL,
 Phone        nvarchar(20),

 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
)
COMMENT = 'Basic information 
about Customer';
