-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** Dim
CREATE TABLE Dim
(
 FromDts   timestamp_ntz(9) NOT NULL,
 ToDts     timestamp_ntz(9) NOT NULL,
 Usernames varchar(50) NOT NULL, -- From template: "Meta"
 LoadDts   timestamp_ntz(9) NOT NULL,
 New        NOT NULL,

 CONSTRAINT Pk1 PRIMARY KEY ( FromDts )
);
