-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** Dim1
CREATE TABLE Dim1
(
 FromDts1  timestamp_ntz(9) NOT NULL,
 ToDts     timestamp_ntz(9) NOT NULL,
 Usernames varchar(50) NOT NULL, -- From template: "Meta"
 LoadDts   timestamp_ntz(9) NOT NULL,

 CONSTRAINT Pk1 PRIMARY KEY ( FromDts1 )
);
