-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Branch 3 by retinder.labana@sqldbm.com ****

-- ************************************** Dim_Supplier
CREATE TABLE Dim_Supplier
(
 SupplierId  bigint NOT NULL CONSTRAINT PK_Supplier_Id PRIMARY KEY,
 CompanyName string NOT NULL,
 Phone       string
)
USING DELTA
 PARTITIONED BY (CompanyName)
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Supplier
  FOR COLUMNS(SupplierId)
;

