-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Branch 3 by retinder.labana@sqldbm.com ****

-- ************************************** Dim_Customer
CREATE TABLE Dim_Customer
(
 CustomerId   bigint NOT NULL CONSTRAINT PK_Dim_Customer PRIMARY KEY,
 CustomerName string NOT NULL,
 Phone        string
)
USING DELTA
 PARTITIONED BY (CustomerName)
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Customer
  FOR COLUMNS(CustomerId)
;

