-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Branch 3 by retinder.labana@sqldbm.com ****

-- ************************************** Dim_Product
CREATE TABLE Dim_Product
(
 ProductId    bigint NOT NULL CONSTRAINT PK_Product_Id PRIMARY KEY,
 ProductName  string NOT NULL,
 IsDiscounted boolean NOT NULL
)
USING DELTA
 PARTITIONED BY (ProductName)
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Product
  FOR COLUMNS(ProductId)
;

