-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Branch 3 by retinder.labana@sqldbm.com ****

-- ************************************** Dim_Order
CREATE TABLE Dim_Order
(
 OrderId     bigint NOT NULL CONSTRAINT PK_Dim_Order PRIMARY KEY,
 OrderNumber string NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Order
  FOR COLUMNS(OrderId)
;

