-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** DimOrder
CREATE TABLE DimOrder
(
 OrderId     int NOT NULL,
 OrderNumber string NOT NULL,

 CONSTRAINT PkDImOrder PRIMARY KEY ( OrderId )
)
STAGE_FILE_FORMAT = 
(
 FORMAT_NAME = 'CsvFileFormat'
);
