-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** DimProduct
CREATE TABLE DimProduct
(
 ProductId      int NOT NULL,
 ProductName    string NOT NULL,
 IsDiscontinued boolean NOT NULL,

 CONSTRAINT PkProduct PRIMARY KEY ( ProductId )
)
STAGE_FILE_FORMAT = 
(
 TYPE = JSON
);
