-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** DimSupplier
CREATE TABLE DimSupplier
(
 SupplierId  int NOT NULL,
 CompanyName string NOT NULL,
 Phone       string,

 CONSTRAINT PkDimSupplier PRIMARY KEY ( SupplierId )
)
STAGE_FILE_FORMAT = 
(
 FORMAT_NAME = 'CsvFileFormat'
);
