-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Snowflake Demo, v45 by retinder.labana@sqldbm.com *


-- ************************************** EDW.sqldbm_DimDepartmentGroup
CREATE TABLE EDW.sqldbm_DimDepartmentGroup
(
 DepartmentGroupKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentDepartmentGroupKey number(38,0),
 DepartmentGroupName      varchar(50) COMMENT 'The name of the department group',
 id                       integer NOT NULL,
 add_coul                 integer NOT NULL,
 id_1                     integer NOT NULL,

 CONSTRAINT PK_DimDepartmentGroup_sqldbm_DimDepartmentGroup PRIMARY KEY ( DepartmentGroupKey )
)
COMMENT = 'Added new comment';
