-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** employeeReselling
CREATE TABLE employeeReselling
(
 EmployeeKey number(38,0) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_37 FOREIGN KEY ( EmployeeKey ) REFERENCES ADWORKS."Dim Employee" ( EmployeeKey )
)
COMMENT = 'AAA';
