-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Branch 3 by retinder.labana@sqldbm.com ****

-- ************************************** Fact_Customer_Orders
CREATE TABLE Fact_Customer_Orders
(
 OrderId    bigint NOT NULL CONSTRAINT FK_4 REFERENCES Dim_Order,
 CustomerId bigint NOT NULL CONSTRAINT FK_3 REFERENCES Dim_Customer,
 ProductId  bigint NOT NULL CONSTRAINT FK_6 REFERENCES Dim_Product,
 SupplierId bigint NOT NULL CONSTRAINT FK_5 REFERENCES Dim_Supplier,
 Price      decimal NOT NULL,
 Quantity   int NOT NULL,
 Profit     bigint NOT NULL,
 Date       date NOT NULL,
 CONSTRAINT PK_6 PRIMARY KEY (OrderId, CustomerId, ProductId, SupplierId)
)
USING DELTA
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Complex');

ALTER TABLE Fact_Customer_Orders ADD CONSTRAINT Check_1 CHECK (Date < '2021-07-01');
ALTER TABLE Fact_Customer_Orders ADD CONSTRAINT Check_2 CHECK (Quantity < 100);

CREATE BLOOMFILTER INDEX
  ON TABLE Fact_Customer_Orders
  FOR COLUMNS(Profit)
;

