-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** FactCustomerOrders
CREATE TABLE FactCustomerOrders
(
 CustomerId int NOT NULL,
 OrderId    int NOT NULL,
 DateId     int NOT NULL,
 SupplierId int NOT NULL,
 ProductId  int NOT NULL,
 Price      decimal NOT NULL,
 Quantity   int NOT NULL,
 Profit     decimal NOT NULL,

 CONSTRAINT PkFactCustomerOrders PRIMARY KEY ( CustomerId, OrderId, DateId, SupplierId, ProductId ),
 CONSTRAINT FkFactCustomerOrdersCustomerId FOREIGN KEY ( CustomerId ) REFERENCES DimCustomer ( CustomerId ),
 CONSTRAINT FkFactCustomerOrdersDateId FOREIGN KEY ( DateId ) REFERENCES DimDate ( DateId ),
 CONSTRAINT FkFactCustomerOrdersOrderId FOREIGN KEY ( OrderId ) REFERENCES DimOrder ( OrderId ),
 CONSTRAINT FkFactCustomerOrdersProductId FOREIGN KEY ( ProductId ) REFERENCES DimProduct ( ProductId ),
 CONSTRAINT FkFactCustomerOrdersSupplierId FOREIGN KEY ( SupplierId ) REFERENCES DimSupplier ( SupplierId )
)
STAGE_FILE_FORMAT = 
(
 FORMAT_NAME = 'CsvFileFormat'
);
