-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** Hub
CREATE TABLE Hub
(
 Md5Hub  binary NOT NULL,
 LoadDts timestamp_ntz(9) NOT NULL,
 RecSrc  varchar(16777216) NOT NULL,

 CONSTRAINT Pk1 PRIMARY KEY ( Md5Hub )
);
