-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** hub_
CREATE TABLE hub_
(
 md5_hub_ binary NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL,
 rec_src  varchar(16777216) NOT NULL,
 username varchar NOT NULL, -- From template: "metadata"

 CONSTRAINT PK_1 PRIMARY KEY ( md5_hub_ )
);
