-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** hub_
CREATE TABLE hub_
(
 md5_hub_ binary NOT NULL CONSTRAINT PK_8 PRIMARY KEY,
 load_dts timestamp_ntz(9) NOT NULL,
 rec_src  string NOT NULL
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
