-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: Sample Project by retinder.labana@sqldbm.com *

-- ************************************** lnk_
CREATE TABLE lnk_
(
 md5_lnk_ binary NOT NULL,
 md5_hub_ binary NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL,
 rec_src  varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_lnk_ )
);
