-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Branch 3 by retinder.labana@sqldbm.com ****

-- ************************************** lnk_
CREATE TABLE lnk_
(
 md5_hub_        binary NOT NULL CONSTRAINT PK_6_1 PRIMARY KEY,
 md5_hub__1      binary NOT NULL,
 load_dts        timestamp_ntz(9) NOT NULL,
 rec_src         string NOT NULL,
 new_col_branch3 int NOT NULL
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
