-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** marts.stores
CREATE TABLE marts.stores
(
 store_id   int NOT NULL CONSTRAINT pk_1_3 PRIMARY KEY,
 store_name string NOT NULL,
 phone      string,
 email      string,
 street     string,
 city       string,
 state      string,
 zip_code   string
)
USING DELTA
 COMMENT 'table includes the store’s information. Each store has a store name, contact information such as phone and email, and an address including street, city, state, and zip code.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
