-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** marts.fct_order_items
CREATE TABLE marts.fct_order_items
(
 item_id    int NOT NULL CONSTRAINT pk_7 PRIMARY KEY,
 order_id   int NOT NULL CONSTRAINT FK_7 REFERENCES marts.orders,
 product_id int NOT NULL CONSTRAINT fk_8 REFERENCES products.products,
 quantity   int NOT NULL,
 list_price decimal(10,2) NOT NULL,
 discount   decimal(4,2) NOT NULL
)
USING DELTA
 COMMENT 'table stores the line items of a sales order. Each line item belongs to a sales order specified by the order_id column.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
