-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** marts.customers
CREATE TABLE marts.customers
(
 custkey               int NOT NULL COMMENT 'Customer Identifier sourced from Salesforce.' CONSTRAINT pk_1_2 PRIMARY KEY,
 nationkey             bigint NOT NULL,
 regionkey             bigint NOT NULL,
 GeographyKey          decimal(38,0) NOT NULL COMMENT 'Geographic informatio',
 CustomerAlternateKey  string NOT NULL COMMENT 'Alternate Key',
 Title                 string COMMENT 'Title of the Customer',
 FirstName             string COMMENT 'Name of the customer',
 MiddleName            string COMMENT 'Middle name of the customer',
 LastName              string COMMENT 'Surname of the customer',
 NameStyle             string COMMENT 'Prefered name',
 BirthDate             date COMMENT 'The birtday of the client',
 MaritalStatus         string COMMENT 'Married/Single',
 Suffix                string COMMENT 'Appendix of the name',
 Gender                string COMMENT 'F/M',
 EmailAddress          string COMMENT 'e-mail address of the client',
 YearlyIncome          decimal(38,0) COMMENT 'Brute annual income',
 TotalChildren         decimal(38,0) COMMENT 'The number of children',
 DECIMALChildrenAtHome decimal(38,0) COMMENT 'The number of children who live with that client',
 EnglishEducation      string COMMENT 'Yes/No',
 SpanishEducation      string COMMENT 'Yes/No',
 FrenchEducation       string COMMENT 'Yes/No',
 EnglishOccupation     string COMMENT 'Yes/No',
 SpanishOccupation     string COMMENT 'Yes/No',
 FrenchOccupation      string COMMENT 'Yes/No',
 HouseOwnerFlag        string COMMENT 'Yes/No',
 DECIMALCarsOwned      decimal(38,0) COMMENT 'The number of the cars that client has',
 AddressLine           string COMMENT 'Billing address',
 AddressLine2          string COMMENT 'Billing address',
 Phone                 string COMMENT 'Phone number of the client',
 DateFirstPurchase     date COMMENT 'The first time the client bought the product',
 CommuteDistance       string
)
USING DELTA
 COMMENT 'table stores customer’s information including first name, last name, phone, email, street, city, state and zip code.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
