-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** operations.fact_sales

CREATE TABLE operations.fact_sales
(
sale_id     int64 NOT NULL PRIMARY KEY NOT ENFORCED,
quantity    int64,
price       float64,
customer_id int64 REFERENCES operations.dim_customer(customer_id) NOT ENFORCED,
product_id  int64 REFERENCES operations.dim_product(product_id) NOT ENFORCED,
time_id     int64 REFERENCES operations.dim_time(time_id) NOT ENFORCED
)
OPTIONS(friendly_name = 'fact sales');
