-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** operations.fact_inventory

CREATE TABLE operations.fact_inventory
(
inventory_id int64 NOT NULL PRIMARY KEY NOT ENFORCED,
quantity     int64,
location_id  int64 REFERENCES operations.dim_location(location_id) NOT ENFORCED,
product_id   int64 REFERENCES operations.dim_product(product_id) NOT ENFORCED
)
OPTIONS(friendly_name = 'inventory');
