-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_time

CREATE TABLE operations.dim_time
(
time_id       int64 NOT NULL PRIMARY KEY NOT ENFORCED,
date          date,
hour          int64,
day_of_week   string,
time_segments array<struct<start_time time, end_time time>>
)
OPTIONS(friendly_name = 'time');
