-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_customer

CREATE TABLE operations.dim_customer
(
customer_id   int64 PRIMARY KEY NOT ENFORCED,
customer_name string,
email         string,
address       string,
contact_info  struct<phone_number string, social_media array<string>>
)
OPTIONS(friendly_name = 'customer');
