-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_location

CREATE TABLE operations.dim_location
(
location_id int64 NOT NULL PRIMARY KEY NOT ENFORCED,
country     string,
city        string,
coordinates struct<latitude float64, longitude float64>
)
OPTIONS(description = 'List of locations and it's details',
friendly_name = 'location');
