-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_employee

CREATE TABLE operations.dim_employee
(
employee_id   int64 NOT NULL PRIMARY KEY NOT ENFORCED,
employee_name string,
role          string,
skills        array<string>
)
OPTIONS(description = 'Employee List',
friendly_name = 'employee');
