-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_employee

CREATE TABLE operations.dim_employee
(
employee_id   int64 PRIMARY KEY NOT ENFORCED,
employee_name string,
role          string,
skills        array<string>
)
OPTIONS(friendly_name = 'employee');
