-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_channel

CREATE TABLE operations.dim_channel
(
channel_id   int64 PRIMARY KEY NOT ENFORCED,
channel_name string,
demographics array<struct<age int64, gender string>>
)
OPTIONS(friendly_name = 'channel');
