-- ********************************* SqlDBM: BigQuery *********************************
-- * Generated by SqlDBM: Google Big Query Webinar, v10 by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_category

CREATE TABLE operations.dim_category
(
category_id   int64,
category_name string OPTIONS(description = 'name of the category'),
description   string OPTIONS(description = 'description for the category'),
subcategories array<string>
)
OPTIONS(description = 'Category list and it's details',
friendly_name = 'category');
