-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** operations.dim_category

CREATE TABLE operations.dim_category
(
category_id   int64,
category_name string,
description   string,
subcategories array<string>
)
OPTIONS(friendly_name = 'category');
