-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** products.products
CREATE TABLE products.products
(
 product_id   int NOT NULL CONSTRAINT pk_4 PRIMARY KEY,
 product_name string NOT NULL,
 brand_id     int NOT NULL CONSTRAINT fk_3 REFERENCES products.brands,
 category_id  int NOT NULL CONSTRAINT fk_4 REFERENCES products.categories,
 model_year   smallint NOT NULL,
 list_price   decimal(10,2) NOT NULL
)
USING DELTA
 COMMENT 'table stores the product’s information such as name, brand, category, model year, and list price.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
