-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** products.stocks
CREATE TABLE products.stocks
(
 product_id int NOT NULL CONSTRAINT fk_10 REFERENCES products.products,
 store_id   int NOT NULL CONSTRAINT fk_11 REFERENCES marts.stores,
 quantity   int
)
USING DELTA
 COMMENT 'table stores the inventory information i.e. the quantity of a particular product in a specific store.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
