-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** products.categories
CREATE TABLE products.categories
(
 category_id   int NOT NULL CONSTRAINT pk_2 PRIMARY KEY,
 category_name string NOT NULL
)
USING DELTA
 COMMENT 'table stores the bike’s categories such as children bicycles, comfort bicycles, and electric bikes.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
