-- ***************************** SqlDBM: Databricks *****************************
-- * Generated by SqlDBM: Databaricks Demo Sample by retinder.labana@sqldbm.com *

-- ************************************** products.brands
CREATE TABLE products.brands
(
 brand_id   int NOT NULL CONSTRAINT pk_3 PRIMARY KEY,
 brand_name string NOT NULL
)
USING DELTA
 COMMENT 'table stores the brand’s information of bikes, for example, Electra, Haro, and Heller.'
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');
