-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Snowflake Demo, v43 by retinder.labana@sqldbm.com *


-- ************************************** sample_test
CREATE TABLE sample_test
(
 col_1 date NOT NULL, -- From template: "Template"
 id    int NOT NULL
);
