-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "sample"
CREATE OR REPLACE TABLE "sample"
(
 username varchar(50) NOT NULL,
 date     datetime NOT NULL
);
