-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** serge.strct_tbl

CREATE TABLE serge.strct_tbl
(
strct_tbl_id int64 OPTIONS(description = 'An optional INTEGER field'),
struct_col   struct<a array<string> OPTIONS(description = 'A repeated STRING field'), b bool>
)
 PARTITION BY  _PARTITIONDATE 
OPTIONS(expiration_timestamp = TIMESTAMP "2025-01-01T00:00:00.000Z",
partition_expiration_days = 1,
description = 'a table that expires in 2025, with each partition living for 24 hours',
friendly_name = 'strct_tbl');
