-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** `serge_caseInsens.d-1`

CREATE TABLE `serge_caseInsens.d-1`
(
id   int64 NOT NULL PRIMARY KEY NOT ENFORCED,
Name string
)
OPTIONS(friendly_name = 'd-1');
