-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** `serge.d-1`

CREATE TABLE `serge.d-1`
(
id   int64 NOT NULL PRIMARY KEY NOT ENFORCED,
name string
)
OPTIONS(friendly_name = 'd-1');
