-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_43
CREATE OR REPLACE TABLE table_43
(
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 date     datetime NOT NULL -- From template: "UserMeta"

);
