-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_44
CREATE OR REPLACE TABLE table_44
(
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 date     datetime NOT NULL -- From template: "UserMeta"

);
