-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_31_1
CREATE OR REPLACE TABLE table_31_1
(
 username varchar(50) NOT NULL,
 date     datetime NOT NULL,
 col_1    varchar NOT NULL -- From template: "Company"

);
