-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** table_25
CREATE TABLE table_25
(
 username varchar NOT NULL -- From template: "metadata"

);
