-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Snowflake Demo, v45 by retinder.labana@sqldbm.com *


-- ************************************** table_30
CREATE TABLE table_30
(
 col_1 date NOT NULL -- From template: "Template"

);
