-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** table_28
CREATE TABLE table_28
(
 username varchar NOT NULL -- From template: "metadata"

);
