-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_40
CREATE TABLE table_40
(
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 date     datetime NOT NULL, -- From template: "UserMeta"
 col_1    varchar NOT NULL -- From template: "Company"

);
