-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_25
CREATE TABLE table_25
(
 username varchar(50) NOT NULL,
 date     datetime NOT NULL,
 col_1    varchar NOT NULL -- From template: "Company"

);
