-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_27
CREATE TABLE table_27
(
 id       integer NOT NULL DEFAULT Sequence_1.nextval,
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 id_1     integer NOT NULL,
 date     datetime NOT NULL, -- From template: "UserMeta"
 tester   varchar(50) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( id ),
 CONSTRAINT FK_39 FOREIGN KEY ( id_1 ) REFERENCES table_31 ( id )
);
