-- ************************** SqlDBM: Snowflake *************************
-- ******* Generated by SqlDBM: Re-1 by retinder.labana@sqldbm.com ******

-- ************************************** table_6
CREATE TABLE table_6
(

);
