-- ******************************* SqlDBM: BigQuery ******************************
-- * Generated by SqlDBM: Google Big Query Webinar by retinder.labana@sqldbm.com *



-- ************************************** table_27

CREATE TABLE table_27
(
created_by string NOT NULL OPTIONS(description = 'user who created the entery'), -- From template: "meta_data_inherite"
created_on timestamp NOT NULL OPTIONS(description = 'timestamps when the entry was created'), -- From template: "meta_data_inherite"
id         int NOT NULL
)
OPTIONS(friendly_name = 'table_27');
