-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_41
CREATE TABLE table_41
(
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 date     datetime NOT NULL, -- From template: "UserMeta"
 col_1    varchar NOT NULL -- From template: "Company"

);
