-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_31
CREATE OR REPLACE TABLE table_31
(
 id       integer NOT NULL,
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 date     datetime NOT NULL, -- From template: "UserMeta"
 tester   varchar(50) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( id )
);
