-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** table_29
CREATE TABLE table_29
(
 username varchar NOT NULL -- From template: "metadata"

);
