-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Snowflake sample 101 by retinder.labana@sqldbm.com *

-- ************************************** Table7
CREATE TABLE Table7
(
 Usernames varchar(50) NOT NULL -- From template: "Meta"

);
