-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Snowflake Demo, v45 by retinder.labana@sqldbm.com *


-- ************************************** table_28
CREATE TABLE table_28
(
 col_1 date NOT NULL -- From template: "Template"

);
