-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Snowflake Demo 12 by retinder.labana@sqldbm.com *


-- ************************************** table_27
CREATE TABLE table_27
(
 username varchar NOT NULL -- From template: "metadata"

);
