-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_38
CREATE OR REPLACE TABLE table_38
(
 username varchar(50) NOT NULL, -- From template: "UserMeta"
 id       varchar NOT NULL,
 date     datetime NOT NULL -- From template: "UserMeta"

);
