-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of 'Msql server - snowflake' by retinder.labana@sqldbm.com *

-- ************************************** table_6
CREATE TABLE table_6
(

);
