-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Snowflake Demo, v43 by retinder.labana@sqldbm.com *


-- ************************************** table_32
CREATE TABLE table_32
(
 col_1 date NOT NULL -- From template: "Template"

);
