-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: Sample Project by retinder.labana@sqldbm.com *

-- ************************************** x
CREATE TABLE x
(
 col1 integer
);
